name: "tests"
on: ["push", "pull_request"]
jobs:
  tests:
    name: npm test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 15
    - name: npm install
      run: npm install
    - name: npm test
      run: npm test

  bundle:
    name: npm run bundle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 15
    - name: Install Meteor
      run: curl https://install.meteor.com | /bin/sh
    - name: npm create bundle
      run: npm run bundle
